apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
spec:
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
        - name: spring-boot-demo
          image: bhoirmakarand/testk8s:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9091
