version: "3.0"

services:
  app:
    image: nginx
    ports:
      - 80
    # deploy:
    #   replicas: 3

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: makarand
      MYSQL_PASSWORD: makarand@1234
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: sampledb
    ports:
      - 3306
